---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-replacer-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  selector:
    matchLabels:
      app: word-replacer-api
  template:
    metadata:
      labels:
        app: word-replacer-api
    spec:
      imagePullSecrets:
          - name: imagepullsecret
      containers:
        - name: word-replacer-api
          image: '349115202997.dkr.ecr.us-east-1.amazonaws.com/word_replacer_api'
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "0.5Gi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: word-replacer-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: word-replacer-api